services:
 backend:
  build: ./martdb
  image: pranulrathour/mymartdb
  restart: always
  networks:
   - mynet
 frontend:
  build: ./My-Mart
  image: pranulrathour/mymart
  restart: always
  networks:
   - mynet
  ports:
   - "3000:80"
  depends_on: 
   - backend

networks:
 mynet:
